language: generic

env:
  - CPPFLAGS="-DH5_NO_DEPRECATED_SYMBOLS"

matrix:
  include:
    # precise: fgsl
    # no updater
    # with gui
    # no notifications
    - os: linux
      sudo: required
      dist: precise
      addons:
        apt:
          sources:
            - sourceline: 'deb [arch=amd64] http://lvserver.ugent.be/apt/ubuntu precise stable'
              key_url: 'http://lvserver.ugent.be/apt/xmi.packages.key'
          packages:
            - libgsl0-dev
            - libfgsl0
            - libfgsl0-dev
            - libgtkextra3
            - libgtkextra3-dev
            - gfortran
            - libxslt1-dev
            - libhdf5-serial-dev
            - hdf5-tools
            - libxrl7-dev
            - libcurl4-openssl-dev
      env: EXTRA='--enable-gui --disable-updater --disable-notifications'
    # precise: fgsl
    # no updater
    # no gui
    # no notifications
    - os: linux
      sudo: required
      dist: precise
      addons:
        apt:
          sources:
            - sourceline: 'deb [arch=amd64] http://lvserver.ugent.be/apt/ubuntu precise stable'
              key_url: 'http://lvserver.ugent.be/apt/xmi.packages.key'
          packages:
            - libgsl0-dev
            - libfgsl0
            - libfgsl0-dev
            - gfortran
            - libxslt1-dev
            - libhdf5-serial-dev
            - hdf5-tools
            - libxrl7-dev
            - libcurl4-openssl-dev
      env: EXTRA='--disable-gui --disable-updater --disable-notifications'
    # precise: fgsl
    # with updater
    # with gui
    # with notifications
    - os: linux
      sudo: required
      dist: precise
      addons:
        apt:
          sources:
            - sourceline: 'deb [arch=amd64] http://lvserver.ugent.be/apt/ubuntu precise stable'
              key_url: 'http://lvserver.ugent.be/apt/xmi.packages.key'
          packages:
            - libgsl0-dev
            - libfgsl0
            - libfgsl0-dev
            - libgtkextra3
            - libgtkextra3-dev
            - gfortran
            - libxslt1-dev
            - libhdf5-serial-dev
            - hdf5-tools
            - libxrl7-dev
            - libcurl4-openssl-dev
            - libjson-glib-dev
            - libnotify-dev
      env: EXTRA='--disable-gui --enable-updater --enable-notifications'

#before_install:
#  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get --yes --force-yes update && sudo apt-get --yes --force-yes install python-all-dev python-numpy cython python3-all-dev python3-numpy swig fpc gfortran php5-dev lua5.2 liblua5.2-dev ; fi
#  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install homebrew/versions/gcc5 swig ruby python python3 fpc lua && pip install Cython numpy && pip3 install numpy ; fi

script:
  - autoreconf -fi
  - ./configure ${EXTRA} && make && make check && make distcheck

notifications:
  email:
    recipients:
      - Tom.Schoonjans@me.com
    on_success: never
    on_failure: always

