language: generic

services:
  - docker

env:
  global:
    - CPPFLAGS="-DH5_NO_DEPRECATED_SYMBOLS"
    - CXXFLAGS="-Wno-deprecated -Wno-deprecated-declarations -Wimplicit  -Wimplicit-function-declaration  -Wimplicit-int"
    - CFLAGS="-Wno-deprecated -Wno-deprecated-declarations -Wimplicit  -Wimplicit-function-declaration  -Wimplicit-int"
    - LD_LIBRARY_PATH='/usr/local/lib'
    - PKG_CONFIG_PATH='/usr/local/lib/pkgconfig'
    - GTKMM_PLPLOT_BRANCH='master'

matrix:
  include:

    # xenial: fgsl and gtkmm-plplot
    # no updater
    # with gui
    - os: linux
      sudo: required
      dist: trusty
      env: EXTRA='--enable-gui --disable-updater' DOCKER_IMAGE_TAG='xenial.with-fgsl.with-gtkmm-plplot.disable-updater.enable-gui'
    # xenial: fgsl and gtkmm-plplot
    # with updater
    # with gui
    - os: linux
      sudo: required
      dist: trusty
      env: EXTRA='--enable-gui --enable-updater' DOCKER_IMAGE_TAG='xenial.with-fgsl.with-gtkmm-plplot.enable-updater.enable-gui'
    # xenial: fgsl
    # no updater
    # no gui
    - os: linux
      sudo: required
      dist: trusty
      env: EXTRA='--disable-gui --disable-updater' DOCKER_IMAGE_TAG='xenial.with-fgsl.without-gtkmm-plplot.disable-updater.disable-gui'
    # xenial: easyRNG and gtkmm-plplot
    # no updater
    # with gui
    - os: linux
      sudo: required
      dist: trusty
      env: EXTRA='--enable-gui --disable-updater' DOCKER_IMAGE_TAG='xenial.with-easyRNG.with-gtkmm-plplot.disable-updater.enable-gui'
    # xenial: easyRNG and gtkmm-plplot
    # with updater
    # with gui
    - os: linux
      sudo: required
      dist: trusty
      env: EXTRA='--enable-gui --enable-updater' DOCKER_IMAGE_TAG='xenial.with-easyRNG.with-gtkmm-plplot.enable-updater.enable-gui'
    # xenial: easyRNG
    # no updater
    # no gui
    - os: linux
      sudo: required
      dist: trusty
      env: EXTRA='--disable-gui --disable-updater' DOCKER_IMAGE_TAG='xenial.with-easyRNG.without-gtkmm-plplot.disable-updater.disable-gui'
    # centos7: fgsl and gtkmm-plplot
    # no updater
    # with gui
    # with google-analytics
    - os: linux
      sudo: required
      dist: trusty
      env: EXTRA='--enable-gui --disable-updater --enable-google-analytics' DOCKER_IMAGE_TAG='centos7.with-fgsl.with-gtkmm-plplot.disable-updater.enable-gui'
    # centos7: fgsl and gtkmm-plplot
    # with updater
    # with gui
    # with google-analytics
    - os: linux
      sudo: required
      dist: trusty
      env: EXTRA='--enable-gui --enable-updater --enable-google-analytics' DOCKER_IMAGE_TAG='centos7.with-fgsl.with-gtkmm-plplot.enable-updater.enable-gui'
    # centos7: fgsl
    # no updater
    # no gui
    # with google-analytics
    - os: linux
      sudo: required
      dist: trusty
      env: EXTRA='--disable-gui --disable-updater --enable-google-analytics' DOCKER_IMAGE_TAG='centos7.with-fgsl.without-gtkmm-plplot.disable-updater.disable-gui'
    # xenial: fgsl
    # no updater
    # no gui
    # with MPI
    - os: linux
      sudo: required
      dist: trusty
      env: EXTRA='--disable-gui --disable-updater --enable-mpi' DOCKER_IMAGE_TAG='xenial.with-fgsl.without-gtkmm-plplot.disable-updater.disable-gui.with-mpi'
    # xenial: easyRNG
    # no updater
    # no gui
    # with MPI
    - os: linux
      sudo: required
      dist: trusty
      env: EXTRA='--disable-gui --disable-updater --enable-mpi' DOCKER_IMAGE_TAG='xenial.with-easyRNG.without-gtkmm-plplot.disable-updater.disable-gui.with-mpi'
    # centos7: fgsl
    # no updater
    # no gui
    # with google-analytics
    # with MPI
    - os: linux
      sudo: required
      dist: trusty
      env: MPICC='/usr/lib64/openmpi/bin/mpicc' EXTRA='--disable-gui --disable-updater --enable-google-analytics --enable-mpi' DOCKER_IMAGE_TAG='centos7.with-fgsl.without-gtkmm-plplot.disable-updater.disable-gui.with-mpi'
    ###
    ###
    ### Mac OS X
    ###
    ###
    # macOS 10.12 Sierra: fgsl
    # no gui
    # no openCL
    - os: osx
      sudo: required
      osx_image: xcode9.2 # macOS 10.12 Sierra
      env: EXTRA='--disable-gui --disable-updater --disable-mac-integration --disable-opencl' MYCC='/usr/local/opt/llvm/bin/clang' MYCXX='/usr/local/opt/llvm/bin/clang++' MYFC='gfortran' HOMEBREW_GCC='gcc llvm' MYLIBS='-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib' BUILD_XRL_AND_FGSL_FROM_SOURCE='yes'

    # macOS 10.12 Sierra: fgsl
    # no gui
    # with openCL
    - os: osx
      sudo: required
      osx_image: xcode9.2 # macOS 10.12 Sierra
      env: EXTRA='--disable-gui --disable-updater --disable-mac-integration --enable-opencl' MYCC='/usr/local/opt/llvm/bin/clang' MYCXX='/usr/local/opt/llvm/bin/clang++' MYFC='gfortran' HOMEBREW_GCC='gcc llvm' MYLIBS='-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib' BUILD_XRL_AND_FGSL_FROM_SOURCE='yes'

    # macOS 10.12 Sierra: easyRNG
    # no gui
    # no openCL
    - os: osx
      sudo: required
      osx_image: xcode9.2 # macOS 10.12 Sierra
      env: EXTRA='--disable-gui --disable-updater --disable-mac-integration --disable-opencl' MYCC='/usr/local/opt/llvm/bin/clang' MYCXX='/usr/local/opt/llvm/bin/clang++' MYFC='gfortran' HOMEBREW_GCC='gcc llvm' MYLIBS='-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib' BUILD_XRL_AND_EASYRNG_FROM_SOURCE='yes'

    # macOS 10.12 Sierra: easyRNG
    # no gui
    # with openCL
    - os: osx
      sudo: required
      osx_image: xcode9.2 # macOS 10.12 Sierra
      env: EXTRA='--disable-gui --disable-updater --disable-mac-integration --enable-opencl' MYCC='/usr/local/opt/llvm/bin/clang' MYCXX='/usr/local/opt/llvm/bin/clang++' MYFC='gfortran' HOMEBREW_GCC='gcc llvm' MYLIBS='-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib' BUILD_XRL_AND_EASYRNG_FROM_SOURCE='yes'

    # macOS 10.12 Sierra: easyRNG
    # with gui
    # no updater
    # no mac-integration
    # no openCL
    # no google analytics
    - os: osx
      sudo: required
      osx_image: xcode9.2 # macOS 10.12 Sierra
      env: EXTRA='--enable-gui --disable-updater --disable-mac-integration --disable-opencl --disable-google-analytics' HOMEBREW_EXTRA='tschoonj/tap/gtkmm-plplot' MYCC='/usr/local/opt/llvm/bin/clang' MYCXX='/usr/local/opt/llvm/bin/clang++' MYFC='gfortran' HOMEBREW_GCC='gcc llvm' MYLIBS='-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib' BUILD_XRL_AND_EASYRNG_FROM_SOURCE='yes'

    # macOS 10.12 Sierra: easyRNG
    # with gui
    # with updater
    # with mac-integration
    # no openCL
    # no google analytics
    - os: osx
      sudo: required
      osx_image: xcode9.2 # macOS 10.12 Sierra
      env: EXTRA='--enable-gui --enable-updater --enable-mac-integration --disable-opencl --disable-google-analytics' HOMEBREW_EXTRA='tschoonj/tap/gtkmm-plplot json-glib gtk-mac-integration' MYCC='/usr/local/opt/llvm/bin/clang' MYCXX='/usr/local/opt/llvm/bin/clang++' MYFC='gfortran' HOMEBREW_GCC='gcc llvm' MYLIBS='-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib' BUILD_XRL_AND_EASYRNG_FROM_SOURCE='yes'

    # macOS 10.12 Sierra: easyRNG
    # with gui
    # no updater
    # no mac-integration
    # with openCL
    # no google analytics
    - os: osx
      sudo: required
      osx_image: xcode9.2 # macOS 10.12 Sierra
      env: EXTRA='--enable-gui --disable-updater --disable-mac-integration --enable-opencl --disable-google-analytics' HOMEBREW_EXTRA='tschoonj/tap/gtkmm-plplot' MYCC='/usr/local/opt/llvm/bin/clang' MYCXX='/usr/local/opt/llvm/bin/clang++' MYFC='gfortran' HOMEBREW_GCC='gcc llvm' MYLIBS='-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib' BUILD_XRL_AND_EASYRNG_FROM_SOURCE='yes'

    # macOS 10.12 Sierra: easyRNG
    # with gui
    # with updater
    # with mac-integration
    # with openCL
    # no google analytics
    - os: osx
      sudo: required
      osx_image: xcode9.2 # macOS 10.12 Sierra
      env: EXTRA='--enable-gui --enable-updater --enable-mac-integration --enable-opencl --disable-google-analytics' HOMEBREW_EXTRA='tschoonj/tap/gtkmm-plplot json-glib gtk-mac-integration' MYCC='/usr/local/opt/llvm/bin/clang' MYCXX='/usr/local/opt/llvm/bin/clang++' MYFC='gfortran' HOMEBREW_GCC='gcc llvm' MYLIBS='-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib' BUILD_XRL_AND_EASYRNG_FROM_SOURCE='yes'

    # macOS 10.12 Sierra: easyRNG
    # with gui
    # no updater
    # no mac-integration
    # no openCL
    # with google analytics
    - os: osx
      sudo: required
      osx_image: xcode9.2 # macOS 10.12 Sierra
      env: EXTRA='--enable-gui --disable-updater --disable-mac-integration --disable-opencl --enable-google-analytics' HOMEBREW_EXTRA='tschoonj/tap/gtkmm-plplot' MYCC='/usr/local/opt/llvm/bin/clang' MYCXX='/usr/local/opt/llvm/bin/clang++' MYFC='gfortran' HOMEBREW_GCC='gcc llvm' MYLIBS='-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib' BUILD_XRL_AND_EASYRNG_FROM_SOURCE='yes'

    # macOS 10.12 Sierra: easyRNG
    # with gui
    # with updater
    # with mac-integration
    # no openCL
    # with google analytics
    - os: osx
      sudo: required
      osx_image: xcode9.2 # macOS 10.12 Sierra
      env: EXTRA='--enable-gui --enable-updater --enable-mac-integration --disable-opencl --enable-google-analytics' HOMEBREW_EXTRA='tschoonj/tap/gtkmm-plplot json-glib gtk-mac-integration' MYCC='/usr/local/opt/llvm/bin/clang' MYCXX='/usr/local/opt/llvm/bin/clang++' MYFC='gfortran' HOMEBREW_GCC='gcc llvm' MYLIBS='-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib' BUILD_XRL_AND_EASYRNG_FROM_SOURCE='yes'

    # macOS 10.12 Sierra: easyRNG
    # with gui
    # no updater
    # no mac-integration
    # with openCL
    # with google analytics
    - os: osx
      sudo: required
      osx_image: xcode9.2 # macOS 10.12 Sierra
      env: EXTRA='--enable-gui --disable-updater --disable-mac-integration --enable-opencl --enable-google-analytics' HOMEBREW_EXTRA='tschoonj/tap/gtkmm-plplot' MYCC='/usr/local/opt/llvm/bin/clang' MYCXX='/usr/local/opt/llvm/bin/clang++' MYFC='gfortran' HOMEBREW_GCC='gcc llvm' MYLIBS='-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib' BUILD_XRL_AND_EASYRNG_FROM_SOURCE='yes'

    # macOS 10.12 Sierra: easyRNG
    # with gui
    # with updater
    # with mac-integration
    # with openCL
    # with google analytics
    - os: osx
      sudo: required
      osx_image: xcode9.2 # macOS 10.12 Sierra
      env: EXTRA='--enable-gui --enable-updater --enable-mac-integration --enable-opencl --enable-google-analytics' HOMEBREW_EXTRA='tschoonj/tap/gtkmm-plplot json-glib gtk-mac-integration' MYCC='/usr/local/opt/llvm/bin/clang' MYCXX='/usr/local/opt/llvm/bin/clang++' MYFC='gfortran' HOMEBREW_GCC='gcc llvm' MYLIBS='-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib' BUILD_XRL_AND_EASYRNG_FROM_SOURCE='yes'


before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ] ; then
      brew cask uninstall --force oclint
      brew uninstall --force --ignore-dependencies $(brew list) || exit 1
      brew update || exit 1
      brew cleanup -s || exit 1
      #rm -rf $(brew --cache) || exit 1
      brew install git gsl autoconf automake libtool libxslt hdf5 libsoup wget pygobject3 || exit 1
      brew install $HOMEBREW_GCC || exit 1
      brew install $HOMEBREW_EXTRA librsvg || exit 1
      export CC=$MYCC
      export OBJC=$MYCC
      export CXX=$MYCXX
      export FC=$MYFC
      export LIBS=$MYLIBS
      brew cleanup -s || exit 1
      #rm -rf $(brew --cache) || exit 1
      if [ -n "$GTKMM_PLPLOT_BRANCH" ] ; then
        brew uninstall --force gtkmm-plplot
      fi
    fi

install:
  - |
    if [ "$BUILD_XRL_AND_EASYRNG_FROM_SOURCE" == "yes" ] || [ "$BUILD_XRL_FROM_SOURCE" == "yes" ] || [ "$BUILD_XRL_AND_FGSL_FROM_SOURCE" == "yes" ] ; then
      wget https://xraylib.tomschoonjans.eu/xraylib-3.3.0.tar.gz || exit 1
      tar xfz xraylib-3.3.0.tar.gz || exit 1
      cd xraylib-3.3.0
      ./configure --enable-fortran2003 --disable-static || exit 1
      make -j2 || exit 1
      sudo make install || exit 1
      cd ..
    fi
    if [ "$BUILD_XRL_AND_EASYRNG_FROM_SOURCE" == "yes" ] || [ "$BUILD_EASYRNG_FROM_SOURCE" == "yes" ] ; then
      wget https://github.com/tschoonj/easyRNG/releases/download/easyRNG-1.1/easyRNG-1.1.tar.gz || exit 1
      tar xfz easyRNG-1.1.tar.gz || exit 1
      cd easyRNG-1.1
      ./configure --enable-fortran --disable-static || exit 1
      make -j2 || exit 1
      sudo make install || exit 1
      cd ..
    fi
    if [ "$BUILD_XRL_AND_FGSL_FROM_SOURCE" == "yes" ] || [ "$BUILD_FGSL_FROM_SOURCE" == "yes" ] ; then
      wget http://www.lrz.de/services/software/mathematik/gsl/fortran/download/fgsl-1.2.0.tar.gz || exit 1
      tar xfz fgsl-1.2.0.tar.gz || exit 1
      cd fgsl-1.2.0
      ./configure --disable-static || exit 1
      make || exit 1
      sudo make install || exit 1
      cd ..
    fi
    if [ -n "$GTKMM_PLPLOT_BRANCH" ] && [ -z "$DOCKER_IMAGE_TAG" ] ; then
      git clone -b $GTKMM_PLPLOT_BRANCH --single-branch --depth=1 https://github.com/tschoonj/gtkmm-plplot.git
      cd gtkmm-plplot
      autoreconf -i
      ./configure --disable-static
      make -j2
      sudo make install
      cd ..
    fi

before_script:
  - |
    if [ -n "$DOCKER_IMAGE_TAG" ] ; then
        docker run --name con_job -t -d tomschoonjans/xmimsim-travis-ci:${DOCKER_IMAGE_TAG} /bin/bash
        echo "#!/bin/sh" > script.sh
        echo "set -x -e" >> script.sh
        echo "export CPPFLAGS=\"$CPPFLAGS\"" >> script.sh
        echo "export CXXFLAGS=\"$CXXFLAGS\"" >> script.sh
        echo "export CFLAGS=\"$CFLAGS\"" >> script.sh
        if [ -n "$MPICC" ] ; then
            echo "export MPICC=\"$MPICC\"" >> script.sh
        fi
        echo "autoreconf -fi" >> script.sh
        echo "./configure ${EXTRA} --disable-static" >> script.sh
        echo "make" >> script.sh
        echo "make check" >> script.sh
        echo "make distcheck" >> script.sh
        echo "set +x" >> script.sh
        chmod a+x script.sh
        docker cp . con_job:/root
        docker exec con_job ls -la
        docker exec con_job cat script.sh
    fi
    

script:
  - |
    if [ -n "$DOCKER_IMAGE_TAG" ] ; then
        docker exec con_job ./script.sh
    else
        set -x
        autoreconf -fi
        ./configure ${EXTRA} --disable-static
        make
        make check
        if [ "$TRAVIS_OS_NAME" == "linux" ] ; then make distcheck ; fi
        set +x
    fi

notifications:
  email:
    recipients:
      - Tom.Schoonjans@me.com
    on_success: never
    on_failure: always

branches:
  only:
    - master

